SEPAstanaItStep/Areas/Account/Controllers/HomeController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SEPAstanaItStep.Areas.Account.Models;
using SEPAstanaItStep.Areas.Account.ViewModels;

namespace SEPAstanaItStep.Areas.Account.Controllers
{
    [Area("Account")]
    public class HomeController : Controller
    {
        // [Route("{area}")]  //localhost/Account     localhost/Account/Home    localhost/Account/Home/Index
        //[Route("{area}/{controller}")]
        // [Route("{area}/{controller}/{action}")]

        List<User> user;
        List<Company> companies;

        public HomeController() {
            Company microsoft = new Company(1, "Microsoft", "USA");
            Company meta = new Company(2, "Meta", "USA");
            Company amazon = new Company(3, "Amazon", "USA");

            companies = new List<Company> { microsoft, meta, amazon };

            user = new List<User> {
            new User(1,"Almas", 30, microsoft),
            new User(2,"Miras", 29, meta),
            new User(3,"Nursultan", 31, amazon),
            new User(4,"Dina", 31,microsoft),
            new User(5,"Dinara", 31,meta),
            new User(6,"Aruna", 31,amazon)
            };
        }

        public IActionResult Index(int? companyId)
        {
            List<CompanyModel> compModels = companies.Select(c=> new CompanyModel(c.Id, c.Name)).ToList();
            compModels.Insert(0, new CompanyModel(0, "All"));

            IndexViewModel viewModel = new() { Companies = compModels, User = user };

            if (companyId != null && companyId > 0) { 
            viewModel.User = user.Where(u => u.Work.Id == companyId);
            }

            return View(viewModel); 
        }

        public string Index2(User usr) {     //  localhost/profile/Index2?name=Miras
            return $"{usr.Name}({usr.Age}) - {usr.Work?.Name}";
        }  
        //ModelState.isValid
        // IModelBinder

        // Request.Form["user.name"]
        // RouteData.Values["user.name"]
        // Request.Query["user.name"]
        //
        //
        // [name of parameter].[name of properties]
        // Areas/Account/Views/Home
    }
}

SEPAstanaItStep/Components/UsersListViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace SEPAstanaItStep.Components
{
    public class UsersListViewComponent : ViewComponent
    {
        List<string> users = new List<string>() { "Kazbek","Arman","Olzhas","Dina","Nurai"};
        public IViewComponentResult Invoke() {
            int number = users.Count;

            if (Request.Query.ContainsKey("number")) {
                int.TryParse(Request.Query["number"], out number);  
            }

            ViewBag.Users = users.Take(number);
            ViewData["Header"] = $"Count of users: {number}";
            return View();
        }
    }
}

SEPAstanaItStep/Controllers/HomeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SEPAstanaItStep.Models;
using System;
using System.Diagnostics;
using System.Diagnostics.Contracts;
using SEPAstanaItStep.Filters;

namespace SEPAstanaItStep.Controllers
{
    /*  [Route("Study")]
      [Route("{controller}")]*/
    //[ControllerResourceFilter(int.MinValue)]
    [TypeFilter(typeof(SimpleResourceFilter))]
    [ServiceFilter(typeof(SimpleResourceFilter))]
    public class HomeController : Controller   //ControllerContext   ,  HttpContext,  ActionDescriptor, ModelState,  RouteData 
    {
        private readonly ILogger<HomeController> _logger;
        readonly ITimeService _timeService;

        public HomeController(ILogger<HomeController> logger, ITimeService timeService)
        {
            _logger = logger;
            _timeService = timeService;
        }

        public string Index2() {
            return _timeService.Time;
        }

        public string Index3([FromServices] ITimeService timeService)
        {
            return timeService.Time;
        }   
        [FakeNotFoundResourceFilter]
        public string Index4()
        {
            ITimeService? timeService = HttpContext.RequestServices.GetService<ITimeService>();
            return timeService?.Time ?? "Undefined";
        }
        [Route("Main")]  // Home/Main   Study/Main
        [Route("Index6")] // Home/Index6   Study/Main
        //[SimpleResourceFilter(30, "8v9vdfv9sd5v9fdsb5v9er")]
        
        public string Index6(string controller, string action)
        {
            /*var controller = RouteData.Values["controller"];
            var action = RouteData.Values["action"];*/
            return $"controller: {controller} \t action: {action}";  // View(string? viewName)   ,   View(object? model)   ,  View(string? viewName,object? model)
        }

        //[CheckFilter]
        public string Index7(int id)
        {
            return $"id = {id}";
        }

        // [Route("{controller=Home}/{action=Index}")]   // localhost/Home/Index  or  localhost/Home   or  localhost

        
        public IActionResult Index()
        {
           /* var controller = RouteData.Values["controller"];
            var action = RouteData.Values["action"];*/
            return View();  // View(string? viewName)   ,   View(object? model)   ,  View(string? viewName,object? model)
        }
        [Route("/{id:int}/{name:maxlength(10)}")]
        public IActionResult Hello(int id, string name) {
            return PartialView();
        }

        public string StringForParameter(User[] user)
        {
            string result = "";
            foreach (var u in user)
            { 
            result = $"{result}{u.UserID} {u.UserName}\n";
            }
                return result;   //localhost/Home/StringForParameter?name=Zein&age=18
        }

        public string StringForParameterAsArray(string[] people)
        {
            string result = "";
            foreach (var person in people) {
                result = $"{result}{person};";
            }
            return result;   //localhost/Home/StringForParameter?name=Zein&age=18
        }

        public string StringForParameterAsDictionary(Dictionary<string, string> items)
        {
            string result = "";
            foreach (var item in items)
            {
                result = $"{result}{item};";
            }
            return result;   //localhost/Home/StringForParameter?name=Zein&age=18
        }

        public string StringforRequest()
        {
            string UserID = Request.Query["UserID"];
            string UserName = Request.Query["UserName"];
            return $"UserID: {UserID}, UserName: {UserName}";   //localhost/Home/StringForParameter?name=Zein&age=18
        }


        public async Task InfoAdmin()
        {
           Response.ContentType = "text/html;charset=utf-8";
           System.Text.StringBuilder table = new("<h3>Request Headers</h3> <table>");

            foreach (var header in Request.Headers) {
                table.Append($"<tr> <td>{header.Key}</td> <td>{header.Value}</td></tr>");
            }
            table.Append("</tabel>");

           await Response.WriteAsync(table.ToString());
        }


        [ActionName("QWERTY")]      // localhost/Home/Privacy x
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpGet]
        public async Task GetUsers()
        {
            string content = @"<form method = 'post'>
             <label>User Name: </label>
             <input name='username'><br/>
             <label>Age: </label>
             <input type='number' name='age'><br/>
             <input type='submit' value= 'Send'/> </form>";
            Response.ContentType= "text/html; charset=utf-8";
            await Response.WriteAsync(content);
        }

        [HttpPost]      // [HttpPut], [HttpDelete], [HttpPatch], [HttpHead]
        public string GetUsers(User user)
        {
            return $"{user.UserID}: {user.UserName}";
        }
        // void  IActionResult 

        public IActionResult ExecuteResultSample() {
            return new HtmlResult("<h1> HELLO IT STEP ASTANA </h1>");
        }


        public IActionResult QQQQQ() {

            return new EmptyResult();

        }

        // ContentResult
        //EmptyResult   
        //NoContentResult 
        //FileResult  
        //FileContentResult  
        //ObjectResult
        //StatusCodeResult
        //UnauthorizedResult
        //NotFoundResult
        //NotFoundObjectResult 
        //BadRequestResult
        //BadRequestObjectResult
        //okResult
        //okObjectResult 
        //CreatedResult 
        //CreatedAtActionResult and CreatedAtRouteResult 
        // AcceptedResult
        // AcceptedAtActionbResult and  AcceptedAtRouteResult
        // JsonResult 
        // ParialViewResult 
        // RediredtResult 
        // RedirectToRouteResult and RedirectToActionResult and RedirectToPageResult
        // LoadRedirectResult 
        // ViewCompanentResult 
        // ViewResult


        public IActionResult ContentExample() {
            return Content("Hello IT STEP");
        }

        public JsonResult JsonExample() {
            return Json("Name");
        }

        public IActionResult JsonResultExample() {
            User user = new User(001, "qwerty");
            var jsonOptions = new System.Text.Json.JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true,
                WriteIndented = true
            };
            return Json(user, jsonOptions);
        }


        public IActionResult RedirecttoActionExample() {
            return Redirect("~/Home/ContentExample");
        }

        public IActionResult RedirecttoRouteExample()
        {
            return Redirect("https://github.com/Zh-987/SEPITStepAstana/tree/main/SEPAstanaItStep/Controllers");
        }
        public IActionResult RedirectPermanentExample() {
            return RedirectPermanent("~/Home/ContentExample");
        }
        public IActionResult RedirectLocalExample()
        {
            return LocalRedirect("~/Home/ContentExample");
            //return LocalRedirectPermanent("~/Home/ContentExample");
        }

        public IActionResult RedirectActionEcxamle()
        {
            return RedirectToAction("JsonResultExample", "Home");
        }

        public IActionResult RedirectActionWithParametersEcxamle()
        {
            return RedirectToAction("JsonResultExample", "Home", new { userid = 001, username = "qwerty"});  // /Home/JsonResultExample?userid=001&username=qwerty
        }

        public IActionResult RedirectRouteEcxamle()
        {
            return RedirectToRoute("default", new { controller = "Home", action = "", userid = "", username = "" });
        }
        public IActionResult StatusCodeResult() {
            return StatusCode(401);
        }

        public IActionResult NOtFoundResult()
        {
            return NotFound("Resource not found");
        }
        public IActionResult UnauthorizedResultExample(int age)
        {
            if (age < 18) return Unauthorized(new Error("Access os denied"));
            return Content("Access is available");
        }
        public IActionResult BadResultExample(string? name)
        {
            if (string.IsNullOrEmpty(name)) return BadRequest("Name undefined");
            return Content($"Name: {name}");
        }
             public IActionResult OkResultExample(string? name)
        {
            return Ok("Dont worry, It step students");
        }
        //FileContentResult  VirtualFileResult FileStreamResult   - File()  PhysicalFileResult   -  PysicalFile()
        public IActionResult FileExample() {
            string file_path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Files/text.txt");
            //byte[] array = System.IO.File.ReadAllBytes(file_path);
            FileStream fileStream = new FileStream(file_path, FileMode.Open);
            string file_type = "text/plain";
            string file_name = "text.txt";
            //return PhysicalFile(file_path, file_type, file_name);
            //return File(array, file_type, file_name);
            return File(fileStream, file_type, file_name);
        }
        public IActionResult FileVirtualExample()
        {
            return File("Files/text.txt", "application/octet-stream", "hello.txt");
        }

        // OnActionExecuting() OnActionExecuted()  OnActionExecutionAsync() 
        [HttpGet]
        public IActionResult WorkingWithForms() {
            return View();
        }

        [HttpPost]

SEPAstanaItStep/Views/Home/About.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

SEPAstanaItStep/Views/Home/Hello.cshtml
@model IEnumerable<string>

<h1>HELLO ALL VISITORS OF MY WEB SITE</h1>

<ul>
    @foreach(string i in Model)
    {
        <li>
            @i
        </li>
    }
</ul>

SEPAstanaItStep/Views/Home/Index.cshtml
@inject ITimeService timeService

@{
    ViewData["Title"] = "Home Page";
    User user = new User(123456,"qwerty");
}

<environment names="Development">
    @await Html.PartialAsync("Hello", new List<string>{"Сәлем", "Привет","Hello","Hola"})

    <div class="text-center">
        <h1 class="display-4">Welcome</h1>
        <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    </div>

    <h2>Current Time: @timeService.Time</h2>
    <h2>Users Data</h2>
    <h3>User ID: @user.UserID</h3>
    <h3>User Name: @user.UserName</h3>

    <div-- class="container"> 
        <div class="row">
            <p> Некэшируемое время <b>@DateTime.Now.ToString("HH:mm:ss")</b></p>
        </div>
        <!-- div class="row">
            <cache priority="Microsoft.Extensions.Caching.Memory.CacheItemPriority.NeverRemove" vary-by="@ViewBag.Id" expires-sliding="TimeSpan.FromSeconds(30) ">
                <p> Кэшируемое время <b>DateTime.Now.ToString("HH:mm:ss")</b></p>
            </cache>
        </div-->


        <div class="row">
            <summary>
                <timer/>
                <date></date>
            </summary>
        </div>

        @await Component.InvokeAsync("Timer");

        <p>
            <vc:timer />
        </p>
        @await Component.InvokeAsync("Header");



        @await Component.InvokeAsync("UsersList");
    @section Footer{
        &copy; 2023 - SEPAstanaItStep - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy - All rights reserved</a>
    }
</environment>

<environment names="Production">
    <h1>This project is under of deleopment</h1>
</environment>

SEPAstanaItStep/Views/Home/WorkingWithForms.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h2>User name Form</h2>

<form method="post">
    <p>
        <label>Username:</label>
        <input type="text" name="username" /> <br />
    </p>
    <p>
        <label>Password:</label>
        <input type="password" name="password" /> <br />
    </p>
    <p>
        <label>Age:</label>
        <input type="number" name="age" /> <br />
    </p>
    <p>
        <label>Is Married:</label>
        <input type="checkbox" name="isMarried" value="false" /> <br />
    </p>
    <p>
        <input name="sex" type="radio" value="Male">
        <span>Male</span>
        <input checked="checked" name="sex" type="radio" value="Female">
        <span>Female</span>
    </p><br />
    <p>
        <label> Select Country:</label>
        <select name="country">
            <option value="Kazakhstan">Kazakhstan</option>
            <option value="Ukraine">Ukraine</option>
            <option value="Japan">Japan</option>
        </select>

    </p>
    <p>
        <label>Comment:</label>
        <textarea name="comment" > </textarea> <br />
    </p>
    <p> <input type="submit" value="Submit" /></p>
   
   
</form> 